import { Poppins } from "next/font/google";
import "./globals.css";
import HomeNavbar from "../components/Navbar/HomeNavbar";
import HomeFooter from "@/components/Footer/HomeFooter";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body  className={poppins.className}>
        <HomeNavbar/>
        
        {children}
        < HomeFooter/>
        </body>
    </html>
  );
}
